### ISSUE TITLE
PlayerTeleportEvent Null

### ISSUE THREAD

**Issue by J055Y** [BattlePlugins/BattleArena#115]
I have a plugin on my server that teleports a player back to spawn if they try to leave. I noticed when testing this functionality I got the following error in console.

```
[12:04:15] [Server thread/ERROR]: Could not pass event PlayerTeleportEvent to BattleArena v3.9.16.3
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:311) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:588) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:575) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1060) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1039) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1030) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:899) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPositionLook.a(SourceFile:18) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(SourceFile:144) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(SourceFile:118) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:876) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:869) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(SourceFile:127) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:853) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:793) [craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class mc.alk.arena.alib.battlebukkitlib.PlayerUtil
        at mc.alk.arena.util.PlayerUtil.getID(PlayerUtil.java:134) ~[?:?]
        at mc.alk.arena.controllers.TeleportController.onPlayerTeleport(TeleportController.java:136) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_241]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_241]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_241]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:309) ~[craftbukkit-1.15.2.jar:git-Bukkit-95bd423]
        ... 20 more
```

**Comment by supawiz6991** [comment]
From the output it looks like the plugin is trying to teleport in a way that battlearena cannot handle. This likely won't be fixed in the current iteration of the plugin. The dev team is working on a complete rewrite of the plugin and it is possible this may not be an issue in that version.
