### ISSUE TITLE
1.9

### ISSUE THREAD

**Issue by tara81** [BattlePlugins/BattleArena#66]
BattleTracker doesnt work : Latest:
http://pastebin.com/3B5xnS05
(Herochat intergration fail- theres a new herochat update)

BombArena Errors - Fails to Load:
http://pastebin.com/nHAvVARZ

**Comment by tara81** [comment]
[07:15:54] [Server thread/INFO]: [BattleArena] Enabling BattleArena v3.9.10.5
[07:15:54] [Server thread/INFO]: [BattleArena] v3.9.10.5 enabling!
[07:15:54] [Server thread/ERROR]: Error occurred while enabling BattleArena v3.9.10.5 (Is it up to date?)
java.lang.NoClassDefFoundError: mc/alk/tracker/Tracker
	at mc.alk.arena.util.BTInterface.setTrackerPlugin(BTInterface.java:217) ~[?:?]
	at mc.alk.arena.controllers.plugins.TrackerController.setPlugin(TrackerController.java:30) ~[?:?]
	at mc.alk.arena.listeners.BAPluginListener.loadBattleTracker(BAPluginListener.java:110) ~[?:?]
	at mc.alk.arena.listeners.BAPluginListener.loadAll(BAPluginListener.java:84) ~[?:?]
	at mc.alk.arena.BattleArena.onEnable(BattleArena.java:175) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:291) ~[patched_1.9.jar:git-Paper-473]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:355) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:315) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:405) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:370) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:325) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564) [patched_1.9.jar:git-Paper-473]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]
Caused by: java.lang.ClassNotFoundException: mc.alk.tracker.Tracker
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_51]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.9.jar:git-Paper-473]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.9.jar:git-Paper-473]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_51]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51]
	... 16 more
[07:15:54] [Server thread/INFO]: [BattleArena] Disabling BattleArena v3.9.10.5
[07:15:54] [Server thread/ERROR]: Error occurred while disabling BattleArena v3.9.10.5 (Is it up to date?)
java.lang.NullPointerException
	at mc.alk.arena.BattleArena.onDisable(BattleArena.java:288) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:293) ~[patched_1.9.jar:git-Paper-473]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:355) [patched_1.9.jar:git-Paper-473]
	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:315) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:405) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:370) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:325) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:273) [patched_1.9.jar:git-Paper-473]
	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:564) [patched_1.9.jar:git-Paper-473]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51]

**Comment by Zach443** [comment]
Will look at this when I get home

**Comment by tara81** [comment]
Thanks, it appears to be an issue with battletracker, its broken in 1.9.  So is bombarena.

**Comment by Zach443** [comment]
Does this still occur with the updated version of BT, @tara81 ?

**Comment by tara81** [comment]
yes, i reported it on battletracker tickets also

**Comment by Europia79** [comment]
i just fixed the BombArena error:
https://github.com/Europia79/Demolition/commit/5bf571ae3bd93d33e0e31366991edfa5823a9934

Here's the download:
http://rainbowcraft.sytes.net/download/plugins/BombArena/v1.2.4/
