### ISSUE TITLE
World.spawnCreature 1.9

### ISSUE THREAD

**Issue by seema84** [BattlePlugins/BattleArena#68]
[02:15:52 WARN]: java.lang.NoSuchMethodException: org.bukkit.World.spawnCreature(org.bukkit.Location, org.bukkit.entity.EntityType)
[02:15:52 WARN]: 	at java.lang.Class.getMethod(Class.java:1786)
[02:15:52 WARN]: 	at mc.alk.arena.objects.spawns.EntitySpawn.<clinit>(EntitySpawn.java:32)
[02:15:52 WARN]: 	at mc.alk.arena.serializers.SpawnSerializer.parseSpawnable(SpawnSerializer.java:136)
[02:15:52 WARN]: 	at mc.alk.arena.serializers.SpawnSerializer.getSpawnList(SpawnSerializer.java:73)
[02:15:52 WARN]: 	at mc.alk.arena.serializers.SpawnSerializer.parseSpawnGroup(SpawnSerializer.java:61)
[02:15:52 WARN]: 	at mc.alk.arena.serializers.SpawnSerializer.loadAll(SpawnSerializer.java:48)
[02:15:52 WARN]: 	at mc.alk.arena.serializers.SpawnSerializer.setConfig(SpawnSerializer.java:35)
[02:15:52 WARN]: 	at mc.alk.arena.BattleArena.onEnable(BattleArena.java:217)
[02:15:52 WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[02:15:52 WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[02:15:52 WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[02:15:52 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361)
[02:15:52 WARN]: 	at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321)
[02:15:52 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411)
[02:15:52 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376)
[02:15:52 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331)
[02:15:52 WARN]: 	at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269)
[02:15:52 WARN]: 	at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527)
[02:15:52 WARN]: 	at java.lang.Thread.run(Thread.java:745)

**Comment by Zach443** [comment]
Thanks for the report. I'm out of town until Saturday. I will look into this as soon as I get back.
