### ISSUE TITLE
Forcestart error

### ISSUE THREAD

**Issue by Pigna** [BattlePlugins/BattleArena#89]
On arena forcestart (this case CTF) a error apears. Noticed this when testing the plugin on:
This server is running CraftBukkit version git-Spigot-625bc00-d09304e (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT)

Arena actualy starts and is playable. but gives a lagspike when starting.

Pluginlist:
AntiXRay, LogBlock, GroupManager, HearthStone, Announcer, Warsong, ProtocolLib, SQLibrary, mcMMO, Vault, InfernalMobs, Essentials, BattleTracker, CompatNoCheatPlus, BattleArena, PerWorldInventory, KingKits, NoCheatPlus, AuctionHouse, ArenaCTF, EssentialsProtect, EssentialsChat, EssentialsAntiBuild, EssentialsSpawn, VeinMiner

[18:04:49 INFO]: [ArenaCTF] Disabling ArenaCTF v1.3.2
[18:04:49 INFO]: [ArenaCTF] v1.3.2 stopping!
[18:04:49 INFO]: [NoCheatPlus] Disabling NoCheatPlus v3.15.1-RC-sMD5NET-b1084
[18:04:49 INFO]: [CompatNoCheatPlus] [cncp] Removed 1 registered hooks from NoCheatPlus.
[18:04:49 INFO]: [BattleArena] Disabling BattleArena v3.9.10.8
[18:04:49 INFO]: [BattleTracker] Disabling BattleTracker v2.5.9.3

The error: 

[17:57:36 INFO]: Myron_Pigna issued server command: /ctf forcestart Castle
[17:57:36 WARN]: java.lang.NoSuchMethodException: org.bukkit.event.entity.EntityDamageEvent.setDamage(int)
[17:57:36 WARN]:        at java.lang.Class.getMethod(Unknown Source)
[17:57:36 WARN]:        at mc.alk.arena.util.compat.pre.EventHelper.<init>(EventHelper.java:14)
[17:57:36 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[17:57:36 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
[17:57:36 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
[17:57:36 WARN]:        at java.lang.reflect.Constructor.newInstance(Unknown Source)
[17:57:36 WARN]:        at mc.alk.arena.listeners.competition.DamageListener.<clinit>(DamageListener.java:38)
[17:57:36 WARN]:        at mc.alk.arena.controllers.ListenerAdder.addListeners(ListenerAdder.java:36)
[17:57:36 WARN]:        at mc.alk.arena.competition.match.Match.<init>(Match.java:241)
[17:57:36 WARN]:        at mc.alk.arena.competition.match.ArenaMatch.<init>(ArenaMatch.java:66)
[17:57:36 WARN]:        at mc.alk.arena.objects.joining.ArenaMatchQueue$FoundMatch.startMatch(ArenaMatchQueue.java:134)
[17:57:36 WARN]:        at mc.alk.arena.objects.joining.ArenaMatchQueue.addReadyMatch(ArenaMatchQueue.java:210)
[17:57:36 WARN]:        at mc.alk.arena.objects.joining.ArenaMatchQueue.forceStart(ArenaMatchQueue.java:474)
[17:57:36 WARN]:        at mc.alk.arena.objects.joining.ArenaMatchQueue.forceStart(ArenaMatchQueue.java:437)
[17:57:36 WARN]:        at mc.alk.arena.controllers.BattleArenaController.forceStart(BattleArenaController.java:706)
[17:57:36 WARN]:        at mc.alk.arena.executors.BAExecutor.arenaForceStart(BAExecutor.java:1404)
[17:57:36 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[17:57:36 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[17:57:36 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[17:57:36 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[17:57:36 WARN]:        at mc.alk.arena.executors.BaseExecutor.onCommand(BaseExecutor.java:260)
[17:57:36 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[17:57:36 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
[17:57:36 WARN]:        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1353)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1188)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[17:57:36 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[17:57:36 WARN]:        at java.util.concurrent.FutureTask.run(Unknown Source)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[17:57:36 WARN]:        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[17:57:36 WARN]:        at java.lang.Thread.run(Unknown Source)

**Comment by Europia79** [comment]
https://github.com/BattlePlugins/BattleArena/blob/master/src/java/mc/alk/arena/listeners/competition/DamageListener.java#L33

https://ideone.com/tPRoxK

**Comment by Europia79** [comment]
http://rainbowcraft.sytes.net/download/plugins/BattleArena/v3.9.11/

This build should fix the issue with the wrong class being instantiated.

In the past, I have used jdk6 to build BattleArena and all dependencies, however, for this build, I had to use jdk8, but I did try to target 1.6.

Hopefully, this isn't an issue for anyone, but it is something everyone should be aware (what jdk was used versus what jvm you're running).

**Comment by Pigna** [comment]
It could not find any already made arenas at start. Removed arenas file in ArenaCTF. Tryed remaking it same name. Gave error that it already existed. Then tryed joining. Gave me error in console that it could not be found. But it joined anyway. After that worked fine and not getting errors anymore. Seemed like a compatibility issue.

**Comment by Europia79** [comment]
Any chance I could see the errors ?

**Comment by Pigna** [comment]
Been unable to reproduce the error / problem in a test server.
