### ISSUE TITLE
1.13 support

### ISSUE THREAD

**Issue by eirikh1996** [BattlePlugins/BattleArena#98]
I tested this on my 1.13 server, and I got this out in console:
[17:47:49 ERROR]: Error occurred while enabling BattleArena v3.9.10.21 (Is it up to date?)
java.lang.NoClassDefFoundError: com/sk89q/worldedit/Vector
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_191]
        at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_191]
        at mc.alk.arena.alib.worldeditutil.WorldGuardInterface.instantiate(WorldGuardInterface.java:73) ~[?:?]
        at mc.alk.arena.alib.worldeditutil.WorldGuardInterface.newInstance(WorldGuardInterface.java:52) ~[?:?]
        at mc.alk.arena.controllers.plugins.WorldGuardController.<clinit>(WorldGuardController.java:29) ~[?:?]
        at mc.alk.arena.listeners.BAPluginListener.loadWorldEdit(BAPluginListener.java:263) ~[?:?]
        at mc.alk.arena.listeners.BAPluginListener.loadAll(BAPluginListener.java:103) ~[?:?]
        at mc.alk.arena.BattleArena.onEnable(BattleArena.java:175) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:580) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:542) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:420) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:698) [spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldedit.Vector
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_191]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:134) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot-1.13.2.jar:git-Spigot-f56e2e7-4385562]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_191]
        ... 19 more

When will this be 1.13 compatible?

**Comment by RednedEpic** [comment]
The version you are trying to run does not support 1.13. 

Here is a link to a working 1.13 version (what is currently on this GitHub). This is not on the Bukkit/Spigot pages yet and it has not extensively been tested, but it should work just fine.

http://rainbowcraft.sytes.net/maven/repository/mc/alk/BattleArena/3.9.11.0/

**Comment by eirikh1996** [comment]
When is the bukkit page updated?

**Comment by RednedEpic** [comment]
I’m not one of the authors of this plugin, but I’d assume once BattleTracker is updated.

**Comment by Europia79** [comment]
The file on the `rainbowcraft-repo` was built by me.

But I think Zach or Clovis update the Spigot/Bukkit pages ?

**Comment by RednedEpic** [comment]
The plugin has now officially been updated to 1.13 and can be downloaded on both the Bukkit and Spigot pages.
